[2025-08-05T14:44:33.042+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.data_preprocessing manual__2025-08-05T14:44:24.621411+00:00 [queued]>
[2025-08-05T14:44:33.056+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.data_preprocessing manual__2025-08-05T14:44:24.621411+00:00 [queued]>
[2025-08-05T14:44:33.057+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T14:44:33.073+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): data_preprocessing> on 2025-08-05 14:44:24.621411+00:00
[2025-08-05T14:44:33.082+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2025-08-05T14:44:33.087+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'data_preprocessing', 'manual__2025-08-05T14:44:24.621411+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmppz_f2fss']
[2025-08-05T14:44:33.091+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask data_preprocessing
[2025-08-05T14:44:33.171+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline.data_preprocessing manual__2025-08-05T14:44:24.621411+00:00 [running]> on host f0f20e28ca3c
[2025-08-05T14:44:33.278+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarah' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T14:44:24.621411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T14:44:24.621411+00:00'
[2025-08-05T14:44:34.660+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 26, in run_preprocessing
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'preprocessing.components.preprocess', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.
[2025-08-05T14:44:34.686+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=data_preprocessing, execution_date=20250805T144424, start_date=20250805T144433, end_date=20250805T144434
[2025-08-05T14:44:34.714+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task data_preprocessing (Command '['python', '-m', 'preprocessing.components.preprocess', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.; 220)
[2025-08-05T14:44:34.749+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T14:44:34.800+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
