[2025-08-10T15:16:56.306+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_with_dvc.train manual__2025-08-10T15:16:48.185927+00:00 [queued]>
[2025-08-10T15:16:56.319+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_with_dvc.train manual__2025-08-10T15:16:48.185927+00:00 [queued]>
[2025-08-10T15:16:56.319+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-10T15:16:56.337+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): train> on 2025-08-10 15:16:48.185927+00:00
[2025-08-10T15:16:56.344+0000] {standard_task_runner.py:60} INFO - Started process 404 to run task
[2025-08-10T15:16:56.349+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'train_with_dvc', 'train', 'manual__2025-08-10T15:16:48.185927+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/train_with_dvc.py', '--cfg-path', '/tmp/tmp7f0e4b1h']
[2025-08-10T15:16:56.353+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask train
[2025-08-10T15:16:56.423+0000] {task_command.py:423} INFO - Running <TaskInstance: train_with_dvc.train manual__2025-08-10T15:16:48.185927+00:00 [running]> on host 260dcf367a78
[2025-08-10T15:16:56.531+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_with_dvc' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T15:16:48.185927+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T15:16:48.185927+00:00'
[2025-08-10T15:16:56.534+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-10T15:16:56.536+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -e\ncd /opt/***/project\nbash scripts/run_training.sh']
[2025-08-10T15:16:56.549+0000] {subprocess.py:86} INFO - Output:
[2025-08-10T15:16:56.571+0000] {subprocess.py:93} INFO - [INFO] dvc pull...
[2025-08-10T15:17:02.162+0000] {subprocess.py:93} INFO - M       models/xgb_model.pkl
[2025-08-10T15:17:02.163+0000] {subprocess.py:93} INFO - M       evaluation/scores.json
[2025-08-10T15:17:02.164+0000] {subprocess.py:93} INFO - M       data/processed/clean_data.csv
[2025-08-10T15:17:02.164+0000] {subprocess.py:93} INFO - M       data/raw/ingested_data.csv
[2025-08-10T15:17:02.173+0000] {subprocess.py:93} INFO - 4 files modified
[2025-08-10T15:17:02.576+0000] {subprocess.py:93} INFO - [INFO] Lancement de l'entra√Ænement...
[2025-08-10T15:17:02.621+0000] {subprocess.py:93} INFO - /usr/local/bin/python: Error while finding module specification for 'training.components.train' (ModuleNotFoundError: No module named 'training')
[2025-08-10T15:17:02.629+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-10T15:17:02.645+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-10T15:17:02.650+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=train_with_dvc, task_id=train, execution_date=20250810T151648, start_date=20250810T151656, end_date=20250810T151702
[2025-08-10T15:17:02.676+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task train (Bash command failed. The command returned a non-zero exit code 1.; 404)
[2025-08-10T15:17:02.732+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-10T15:17:02.757+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
