[2025-06-24T10:07:56.804+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.model_training manual__2025-06-24T10:07:46.065947+00:00 [queued]>
[2025-06-24T10:07:56.811+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.model_training manual__2025-06-24T10:07:46.065947+00:00 [queued]>
[2025-06-24T10:07:56.812+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-24T10:07:56.825+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2025-06-24 10:07:46.065947+00:00
[2025-06-24T10:07:56.831+0000] {standard_task_runner.py:60} INFO - Started process 239 to run task
[2025-06-24T10:07:56.834+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'model_training', 'manual__2025-06-24T10:07:46.065947+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmphbqmykut']
[2025-06-24T10:07:56.836+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask model_training
[2025-06-24T10:07:56.876+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline.model_training manual__2025-06-24T10:07:46.065947+00:00 [running]> on host c5d82eb3ca4f
[2025-06-24T10:07:56.936+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarah' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T10:07:46.065947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T10:07:46.065947+00:00'
[2025-06-24T10:07:57.496+0000] {logging_mixin.py:188} INFO - ❌ Subprocess failed!
[2025-06-24T10:07:57.497+0000] {logging_mixin.py:188} INFO - ⚠️ STDOUT:
[2025-06-24T10:07:57.498+0000] {logging_mixin.py:188} INFO -  
[2025-06-24T10:07:57.498+0000] {logging_mixin.py:188} INFO - ⚠️ STDERR:
[2025-06-24T10:07:57.498+0000] {logging_mixin.py:188} INFO -  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/***/project/src/training/components/train.py", line 6, in <module>
    from sklearn.model_selection import train_test_split, RandomizedSearchCV
ModuleNotFoundError: No module named 'sklearn'
[2025-06-24T10:07:57.499+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 34, in run_training
    result = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'training.components.train', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.
[2025-06-24T10:07:57.512+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=model_training, execution_date=20250624T100746, start_date=20250624T100756, end_date=20250624T100757
[2025-06-24T10:07:57.524+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task model_training (Command '['python', '-m', 'training.components.train', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.; 239)
[2025-06-24T10:07:57.569+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-24T10:07:57.588+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
