[2025-08-06T07:52:04.538+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.data_preprocessing manual__2025-08-06T07:51:55.936136+00:00 [queued]>
[2025-08-06T07:52:04.551+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.data_preprocessing manual__2025-08-06T07:51:55.936136+00:00 [queued]>
[2025-08-06T07:52:04.552+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-06T07:52:04.573+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): data_preprocessing> on 2025-08-06 07:51:55.936136+00:00
[2025-08-06T07:52:04.579+0000] {standard_task_runner.py:60} INFO - Started process 273 to run task
[2025-08-06T07:52:04.584+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'data_preprocessing', 'manual__2025-08-06T07:51:55.936136+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp3gxhitwz']
[2025-08-06T07:52:04.587+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask data_preprocessing
[2025-08-06T07:52:04.663+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline.data_preprocessing manual__2025-08-06T07:51:55.936136+00:00 [running]> on host f0f20e28ca3c
[2025-08-06T07:52:04.768+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarah' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T07:51:55.936136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T07:51:55.936136+00:00'
[2025-08-06T07:52:05.971+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 26, in run_preprocessing
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'preprocessing.components.preprocess', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.
[2025-08-06T07:52:05.988+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=data_preprocessing, execution_date=20250806T075155, start_date=20250806T075204, end_date=20250806T075205
[2025-08-06T07:52:06.007+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task data_preprocessing (Command '['python', '-m', 'preprocessing.components.preprocess', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.; 273)
[2025-08-06T07:52:06.055+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T07:52:06.083+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
